FROM nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu20.04

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /app
COPY . /app

RUN apt update && apt install -y \
    python3 python3-pip python3-dev \
    git curl libgl1-mesa-glx build-essential cmake \
    && ln -s /usr/bin/python3 /usr/bin/python \
    && pip install --upgrade pip

RUN pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
RUN pip install -r requirements.txt

CMD ["python", "app/query_engine.py"]
