# Frontend service
apiVersion: v1
kind: Service
metadata:
  name: kt-frontend-service
spec:
  selector:
    app: kt-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: LoadBalancer
